version: '3'
services:
  db:
    image: "postgres"
    restart: "always"
    container_name: "postgres_pidb"

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Stephan911!"
      POSTGRES_DB: "postgres"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
     - "postgres"

networks:
  postgres:
    driver: "bridge"

volumes:
  postgres_data: